import { defineConfig } from 'vitepress';
import container from 'markdown-it-container';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

// nav-data.json is generated by tools/prepare-docs.mjs (runs before build/dev)
const navDataPath = fileURLToPath(new URL('./nav-data.json', import.meta.url));
const navData = JSON.parse(readFileSync(navDataPath, 'utf-8')) as Array<{
  file: string; slug: string; group: string; title: string;
}>;

const GROUP_ORDER = ['Bắt đầu', 'Nền tảng Fresher', 'Chuyên sâu', 'Phụ lục'];

function buildSidebar() {
  return GROUP_ORDER.map((group) => ({
    text: group,
    collapsed: false,
    items: navData
      .filter((p) => p.group === group)
      .map((p) => ({ text: shortTitle(p), link: `/${p.slug}` })),
  }));
}

// Shorten long titles for the sidebar (the full title stays at the top of the page)
function shortTitle(p: { slug: string; title: string }): string {
  const m = p.title.match(/^(Chương \d+)\.\s*(.+)$/);
  if (m) return `${m[1]}. ${m[2].split(':')[0].trim()}`;
  if (p.title.startsWith('Nền tảng')) return p.title.replace(' (kiến thức Fresher)', '');
  if (p.slug === 'loi-mo-dau') return 'Lời mở đầu';
  return p.title;
}

export default defineConfig({
  lang: 'vi-VN',
  title: 'Cẩm nang phỏng vấn Java Backend',
  description: 'Từ nền tảng Fresher đến lập trình viên 2–4 năm kinh nghiệm — học gì, học sâu tới đâu, người phỏng vấn thực sự muốn nghe gì.',
  base: '/java-interview-handbook/',
  lastUpdated: true,
  cleanUrls: true,
  head: [['link', { rel: 'icon', href: '/java-interview-handbook/favicon.svg' }]],

  markdown: {
    config: (md) => {
      // ::: answer ... ::: — wraps the sample answer, toggleable in self-check mode
      // ::: recall Title ... ::: — "Nhắc lại kiến thức" (recall) callout, not built into VitePress
      md.use(container, 'recall', {
        render(tokens: any[], idx: number) {
          const token = tokens[idx];
          if (token.nesting === 1) {
            const title = token.info.trim().slice('recall'.length).trim() || 'Nhắc lại kiến thức';
            return `<div class="custom-block recall"><p class="custom-block-title">${md.utils.escapeHtml(title)}</p>\n`;
          }
          return '</div>\n';
        },
      });
      md.use(container, 'answer', {
        render(tokens: any[], idx: number) {
          return tokens[idx].nesting === 1
            ? '<div class="qa-answer"><div class="qa-answer-inner">\n'
            : '</div></div>\n';
        },
      });
    },
  },

  themeConfig: {
    logo: { src: '/logo.svg', width: 24, height: 24 },
    // Navbar title is shorter than `title` (the tab's <title>) so it doesn't overlap the Search button
    siteTitle: 'Cẩm nang Java Backend',
    nav: [
      { text: 'Trang chủ', link: '/' },
      { text: 'Bắt đầu ôn', link: '/loi-mo-dau' },
      { text: 'Nền tảng Fresher', link: '/nen-tang-1' },
      { text: 'Phụ lục', link: '/phu-luc' },
      { text: 'Tải bản Word', link: '/cam-nang-java-backend.docx' },
    ],
    sidebar: buildSidebar(),
    outlineTitle: 'Trên trang này',
    outline: [2, 3],
    returnToTopLabel: 'Về đầu trang',
    sidebarMenuLabel: 'Mục lục',
    darkModeSwitchLabel: 'Giao diện',
    darkModeSwitchTitle: 'Đổi sang giao diện tối',
    lightModeSwitchTitle: 'Đổi sang giao diện sáng',
    lastUpdatedText: 'Cập nhật lần cuối',
    docFooter: { prev: 'Trang trước', next: 'Trang sau' },
    externalLinkIcon: true,

    socialLinks: [
      { icon: 'github', link: 'https://github.com/boy2407/java-interview-handbook' },
    ],

    editLink: {
      // Pages are generated from content/*.md under different names, so map slug -> source file
      pattern: ({ filePath }) => {
        // This function is serialized to the client, so it must not reference outer variables
        const slug = filePath.replace(/\.md$/, '');
        const source =
          slug === 'loi-mo-dau' ? 'ch00.md'
          : slug === 'phu-luc' ? 'ch14.md'
          : slug.startsWith('nen-tang-') ? `fb${slug.slice('nen-tang-'.length)}.md`
          : slug.startsWith('chuong-') ? `ch${slug.slice('chuong-'.length)}.md`
          : 'ch00.md';
        return `https://github.com/boy2407/java-interview-handbook/edit/main/content/${source}`;
      },
      text: 'Góp ý / sửa nội dung trên GitHub',
    },

  },
});
